/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',

    height: 363,
    width: 400,
    layout: {
        type: 'fit'
    },
    title: '新增选课',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '选课名称'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: '课程公告'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '授课教师'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: '学生'
                        },
                        {
                            xtype: 'tabpanel',
                            height: 157,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: '2011级'
                                },
                                {
                                    xtype: 'panel',
                                    title: '2012级'
                                },
                                {
                                    xtype: 'panel',
                                    title: '2013级'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});