/*
 * File: app/store/ResGridStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.ResGridStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ResGridStore',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: '#'
                },
                {
                    name: '名称'
                },
                {
                    name: '格式'
                },
                {
                    name: '大小'
                },
                {
                    name: '关键字'
                },
                {
                    name: '发布者'
                },
                {
                    name: '审核状态'
                },
                {
                    name: '上传时间'
                }
            ]
        }, cfg)]);
    }
});