/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: '新增选课'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 0,
                    height: 71,
                    layout: {
                        columns: 4,
                        type: 'table'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '0 5px 0 0',
                            fieldLabel: '选课名称',
                            labelWidth: 80
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px',
                            fieldLabel: '授课教师',
                            labelWidth: 80
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px',
                            fieldLabel: '学生',
                            labelWidth: 35
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 0 0 5px',
                            fieldLabel: '创建者',
                            labelWidth: 50
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px 0 0',
                            fieldLabel: '创建时间(起)',
                            labelWidth: 80
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px',
                            fieldLabel: '创建时间(止)',
                            labelWidth: 80
                        },
                        {
                            xtype: 'panel',
                            colspan: 2,
                            border: false,
                            layout: {
                                align: 'stretch',
                                pack: 'end',
                                padding: '0 0 0 5px',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '0 5px 0 0',
                                    width: 73,
                                    text: '重置'
                                },
                                {
                                    xtype: 'button',
                                    margins: '0 0 0 5px',
                                    width: 71,
                                    text: '搜索'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    title: '选课列表',
                    store: 'ElectiveCourseGridStore',
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'buttongroup',
                                    title: '通用',
                                    columns: 2,
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: '编辑'
                                        },
                                        {
                                            xtype: 'button',
                                            text: '删除'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'buttongroup',
                                    title: '高级',
                                    columns: 2,
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: '选课作业管理'
                                        },
                                        {
                                            xtype: 'button',
                                            text: '选课问答管理'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '#',
                            text: '#'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '选课名称',
                            text: '选课名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '公告',
                            text: '公告'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '授课教师',
                            text: '授课教师'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '学生',
                            text: '学生'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '创建者',
                            text: '创建者'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '创建时间',
                            text: '创建时间'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});