/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: '新增用户'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: '导入用户模板'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: '下载用户导入模板'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 0,
                    height: 96,
                    layout: {
                        columns: 4,
                        type: 'table'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            padding: '0 5px 0 0',
                            fieldLabel: '帐号',
                            labelWidth: 35
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px',
                            fieldLabel: '真名',
                            labelWidth: 35
                        },
                        {
                            xtype: 'combobox',
                            padding: '0 5px',
                            fieldLabel: '性别',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 0 0 5px',
                            fieldLabel: '邮箱',
                            labelWidth: 35
                        },
                        {
                            xtype: 'combobox',
                            padding: '0 5px 0 0',
                            fieldLabel: '角色',
                            labelWidth: 35
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 5px',
                            fieldLabel: '学号',
                            labelWidth: 35
                        },
                        {
                            xtype: 'combobox',
                            padding: '0 5px',
                            fieldLabel: '入学年份',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            padding: '0 0 0 5px',
                            fieldLabel: '电话',
                            labelWidth: 35
                        },
                        {
                            xtype: 'button',
                            colspan: 4,
                            style: 'float:right;',
                            width: 115,
                            text: '搜索'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    title: 'My Grid Panel',
                    store: 'MyJsonStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '#',
                            text: '#'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '帐号',
                            text: '帐号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '真名',
                            text: '真名'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '性别',
                            text: '性别'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '密码',
                            text: '密码'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '邮箱',
                            text: '邮箱'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '角色',
                            text: '角色'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '学号',
                            text: '学号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '入学年份',
                            text: '入学年份'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: '电话',
                            text: '电话'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'MyJsonStore'
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '编辑'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: '删除'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});